// import 'package:expense_tracker/models/expense.dart';

// List<Expense> dummyExpenses = [
//   // February Transactions
//   Expense(
//     id: '1',
//     name: 'Groceries',
//     desc: 'Bought vegetables and fruits',
//     amount: 1200.50,
//     categoryId: 'food',
//     categoryName: 'Food & Dining',
//     categoryColor: null,
//     type: ExpenseType.Expense,
//     datetime: DateTime.now().subtract(Duration(days: 2, hours: 3, minutes: 15)),
//   ),
//   Expense(
//     id: '2',
//     name: 'Salary',
//     desc: 'Monthly salary credited',
//     amount: 100000.00,
//     categoryId: 'income',
//     categoryName: 'Income',
//     categoryColor: null,
//     type: ExpenseType.Income,
//     datetime: DateTime.now().subtract(Duration(days: 2, hours: 6, minutes: 30)),
//   ),
//   Expense(
//     id: '3',
//     name: 'Netflix Subscription',
//     desc: 'Monthly Netflix renewal',
//     amount: 499.00,
//     categoryId: 'entertainment',
//     categoryName: 'Entertainment',
//     categoryColor: null,
//     type: ExpenseType.Expense,
//     datetime: DateTime.now().subtract(Duration(days: 1, hours: 4, minutes: 45)),
//   ),
//   Expense(
//     id: '4',
//     name: 'Electricity Bill',
//     desc: 'Electricity charges for the month',
//     amount: 2500.00,
//     categoryId: 'utilities',
//     categoryName: 'Utilities',
//     categoryColor: null,
//     type: ExpenseType.Expense,
//     datetime: DateTime.now().subtract(Duration(days: 1, hours: 1, minutes: 20)),
//   ),
//   Expense(
//     id: '5',
//     name: 'Freelance Work',
//     desc: 'Payment for freelance project',
//     amount: 15000.00,
//     categoryId: 'income',
//     categoryName: 'Income',
//     categoryColor: null,
//     type: ExpenseType.Income,
//     datetime: DateTime.now().subtract(Duration(days: 2, hours: 2, minutes: 50)),
//   ),
  
//   // January Transactions
//   Expense(
//     id: '12',
//     name: 'New Year Party',
//     desc: 'Celebration dinner',
//     amount: 3000.00,
//     categoryId: 'entertainment',
//     categoryName: 'Entertainment',
//     categoryColor: null,
//     type: ExpenseType.Expense,
//     datetime: DateTime(2025, 1, 1, 20, 30),
//   ),
//   Expense(
//     id: '13',
//     name: 'Gym Renewal',
//     desc: 'Yearly gym membership',
//     amount: 10000.00,
//     categoryId: 'fitness',
//     categoryName: 'Health & Fitness',
//     categoryColor: null,
//     type: ExpenseType.Expense,
//     datetime: DateTime(2025, 1, 5, 10, 0),
//   ),
//   Expense(
//     id: '14',
//     name: 'Stock Investment',
//     desc: 'Added funds to trading account',
//     amount: 20000.00,
//     categoryId: 'investment',
//     categoryName: 'Investments',
//     categoryColor: null,
//     type: ExpenseType.Expense,
//     datetime: DateTime(2025, 1, 10, 15, 45),
//   ),

//   // December Transactions
//   Expense(
//     id: '15',
//     name: 'Christmas Gifts',
//     desc: 'Bought gifts for family',
//     amount: 5000.00,
//     categoryId: 'shopping',
//     categoryName: 'Shopping',
//     categoryColor: null,
//     type: ExpenseType.Expense,
//     datetime: DateTime(2024, 12, 25, 18, 30),
//   ),
//   Expense(
//     id: '16',
//     name: 'Year-End Bonus',
//     desc: 'Received company bonus',
//     amount: 25000.00,
//     categoryId: 'income',
//     categoryName: 'Income',
//     categoryColor: null,
//     type: ExpenseType.Income,
//     datetime: DateTime(2024, 12, 30, 12, 0),
//   ),
//   Expense(
//     id: '17',
//     name: 'Flight Ticket',
//     desc: 'Vacation trip booking',
//     amount: 15000.00,
//     categoryId: 'travel',
//     categoryName: 'Travel',
//     categoryColor: null,
//     type: ExpenseType.Expense,
//     datetime: DateTime(2024, 12, 15, 9, 30),
//   ),
// ];